name: CI

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  lint-only:
    runs-on: ubuntu-latest
    steps:
      # 1. 檢出程式碼
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 設定 Python 3.12
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 3. 安裝所有檢查工具
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install autoflake isort black ruff flake8

      # 4. Autoflake 檢查（不寫回檔案）
      - name: Autoflake check
        run: |
          autoflake --check --recursive \
            --remove-all-unused-imports \
            --remove-unused-variables .

      # 7. Ruff 檢查（預設 check）
      - name: ruff lint
        run: |
          ruff check .

      # 8. Flake8 檢查（最大行長 125）
      - name: flake8 lint
        run: |
          flake8 . --max-line-length=125
